### ISSUE TITLE
How to fill data_path docs_path ,collection_name?

### ISSUE THREAD

**Issue by aixiaodewugege** [IAAR-Shanghai/CRUD_RAG#10]
Thanks for your brilliant work. Could you please share how to fill these param？And what the meaning of these param?
  
  
  --data_path 'path/to/dataset' \
  --docs_path 'path/to/retrieval_database' \
  --collection_name 'name/of/retrieval_database' \

**Comment by haruhi-sudo** [comment]
collection_name can be filled in as you like, --data_path can be filled in data/crud_split/split_merged.json, --doc_path can be filled in data/80000_docs

**Comment by aixiaodewugege** [comment]
Thanks for your reply!
I notice that you only run part 1 data in your paper. How should I fill  --data_path, --doc_path to reproduce your result?

**Comment by aixiaodewugege** [comment]
> collection_name can be filled in as you like, --data_path can be filled in data/crud_split/split_merged.json, --doc_path can be filled in data/80000_docs

The result I got is as follow:
`{
    "info": {
        "task": "Summary",
        "llm": "{'model_name': 'qwen7b', 'temperature': 0.1, 'max_new_tokens': 1280, 'top_p': 0.9, 'top_k': 5}"
    },
    "overall": {
        "avg. bleu-avg": 0.4899373964017888,
        "avg. bleu-1": 0.7711002085847525,
        "avg. bleu-2": 0.5501802624743161,
        "avg. bleu-3": 0.4339695716889377,
        "avg. bleu-4": 0.35391291064866337,
        "avg. rouge-L": 0.33885416082864706,
        "avg. length": 81.59703075291623,
        "num": 1886
    },`

**Comment by aixiaodewugege** [comment]
> The format seems to be fine, but the average length of the generated results seems to be shorter than the results from the paper. What model did you use and what task did you evaluate?

I use Qwen 7b on summary task.  And the score I got is much lower than your paper.
`Qwen-7B 28.30 30.21 84.26 67.62 40.03 240.5`

**Comment by haruhi-sudo** [comment]
Qwen-7b's ability to follow instructions is relatively weak. In order to make it generate appropriate results instead of meaningless words, you may need to carefully modify the prompt. If you have similar questions, you can email s1583050085@gmail.com

**Comment by aixiaodewugege** [comment]
Are these warning "evaluator:task_generation:50 - IndexError('list index out of range')" cause it?
I think it is not the prompt problem, because bleu score I got is 0.4899, and it is 28.3 in your paper. I am really confused with it.

**Comment by haruhi-sudo** [comment]
Can you send your experimental results to my email?

**Comment by haruhi-sudo** [comment]
I have looked at the generated content and it basically confirmed my guess. The bleu metric is unreliable when the generated content is too short. I will help you solve the problem by email

**Comment by Syno8** [comment]
> > The format seems to be fine, but the average length of the generated results seems to be shorter than the results from the paper. What model did you use and what task did you evaluate?
> 
> I use Qwen 7b on summary task. And the score I got is much lower than your paper. `Qwen-7B 28.30 30.21 84.26 67.62 40.03 240.5`

请问你的问题解决了吗？
我们也发现我们的结果很低

**Comment by haruhi-sudo** [comment]
他是没有传递--construct_index参数，导致没有建立检索数据库
