### ISSUE TITLE
llama_index and langchain version issue

### ISSUE THREAD

**Issue by XinyuYe-Intel** [IAAR-Shanghai/CRUD_RAG#14]
Hi, could you please share the version of llama_index and langchain that you used?
I've tried latest version, but seems llama_index newer than 0.9.48 would be incompatible with your code, so I used llama_index 0.9.36, which appears compatible, but langchain version issue still exists, seems caused by `HuggingfaceEmbeddings` inherited from `langchain.schema.embeddings.Embeddings` does not have `get_agg_embedding_from_queries` function.
![image](https://github.com/user-attachments/assets/1c50f2f0-48b7-4117-bbb7-37412fe69812)

Below is the command I used:
``` bash
python quick_start.py     --temperature 0.1   --max_new_tokens 1280     --shuffle True     --docs_type 'txt'   --docs_path data/80000_docs   --chunk_size 128   --chunk_overlap 0   --retriever_name 'base'   --collection_name milvus_test  --retrieve_top_k 8   --task 'all'   --num_threads 20   --show_progress_bar True   --construct_index
```

**Comment by haruhi-sudo** [comment]
Hello, I have updated the requirement.txt file.

**Comment by XinyuYe-Intel** [comment]
Thanks! It works now.
