### ISSUE TITLE
项目中QA类型为什么用answers 去向量库召回文档，而不是使用questions？

### ISSUE THREAD

**Issue by pluiest** [IAAR-Shanghai/CRUD_RAG#21]
作者你好，我用glm4v跑了一下quest_answer，最后在分析整个项目流程的时候发现一个疑问：

项目中似乎使用的是 split_merged.json 里面的 answers 去做的 retrieval，得到 contrievd_text。在一般的 RAG流程里面，应该是我们拿着用户的问题去做检索吧？这里拿着问题的答案去做检索，检索出来的内容必然会比拿问题来检索要好吧？
请问项目里这样做的原因是基于什么考虑呢？

![1724377696803](https://github.com/user-attachments/assets/333a9993-7682-4e52-886a-1f36a2d50694)

**Comment by haruhi-sudo** [comment]
你好，我们用的就是questions检索，请查看代码： 
https://github.com/IAAR-Shanghai/CRUD_RAG/blob/7df80798cacc85d36b009cc274fa5b386f4444b7/src/tasks/quest_answer.py#L39C1-L40C1

**Comment by pluiest** [comment]
谢谢，是我看错了，😓
