### ISSUE TITLE
Request for Test Set Generation Prompts

### ISSUE THREAD

**Issue by EnzoWuu** [IAAR-Shanghai/CRUD_RAG#4]
Would it be possible for you to provide the prompts used for generating test datasets, or guide me on how I could generate a similar test dataset using your project? Any assistance in this regard would be greatly appreciated. 
您好，请问能提供更多的用于生成测试集(question和answer)的prompt例子吗

**Comment by haruhi-sudo** [comment]
你好，我们使用的prompt与论文中第3.4节的图5所展示的一致。如需进一步了解数据集的生成过程，您可以参考data/crud_split/split_merged.json文件。在该文件中，数据集questanswer_2docs和questanswer_3docs都包含了"thoughts"字段，它详细展示了数据集的生成方式。
